post:
  tags:
  - Products
  summary: Create a product
  description: Create a new product.
  operationId: createProduct
  security:
    - main_auth:
        - 'write:products'
  requestBody:
    content:
      'application/json':
        schema:
          $ref: ../components/schemas/Product.yaml
  responses: 
    '200':
      description: Ok
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '400':
      description: Bad request
    '403':
      description: Forbidden
get:
  tags:
    - Products
  summary: Get a list of products
  description: Get a list of products based on the query parameters.
  operationId: listProducts
  # parameters:
  #   - in: query
  #     name: product_type
  #     schema:
  #       type: string
  #       description: Limit response to a product_type. Case sensitive.
  #       example: auction
  #   - in: query
  #     name: tags
  #     schema:
  #       type: string
  #       description: Limit response to a product_type.
  #       enum: [opensea, notables, featured, sports, art, film, music]
  #   - in: query
  #     name: collection
  #     schema:
  #       type: string
  #       description: Limit response to products of a collection. Case sensitive and must match the collection name exactly. Will return all products in a collection.
  #       example: Race Day 2021
  #   - in: query
  #     name: creator
  #     schema:
  #       type: string
  #       description: Limit response to products of a creator. Case sensitive and must match the creator name exactly.
  #       example: lewishamilton
  #   - in: query
  #     name: status
  #     schema:
  #       type: string
  #       description: Limit response to only products of a specific status.
  #       enum: [active, archived, draft]
  #   - in: query
  #     name: limit
  #     schema:
  #       type: integer
  #       description: Limit. Defaults to 20, capped at 50.
  #       default: 20
  responses: 
    '200':
      description: Ok
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Product.yaml
    '400':
      description: Bad request
    '403':
      description: Forbidden