get:
  tags:
    - Collections
  summary: Get collection by id
  description: Retrieves the details of an existing collection using its id. You need only supply the unique collection identifier that was returned upon collection creation.
  operationId: getCollection
  security:
    - main_auth:
        - 'read:collections'
  parameters:
    - name: id
      in: path
      description: The id of the collection that needs to be fetched.
      required: true
      schema:
        type: string
        example: cd3c2652-4cab-45ef-a805-330aebd36815
  responses: 
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Collection.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorForbidden.yaml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorNotFound.yaml