type: object
properties:
  id:
    type: integer
    example: 40647083557033
  edition:
    type: integer
    example: 1
  edition_of:
    type: integer
    example: 3
  price:
    type: integer
    example: 0.00
  blockchain:
    type: string
    example: rinkeby
  contract_address:
    type: string
    example: '0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656'
  token_id:
    type: integer
    example: 6780